version: "3.3"
services:
    notification-app:
#        image: sapronovps/otus-microservice-architecture:latest
        build:
            context: '.'
            args:
                uid: ${UID}
        container_name: notification-app
        ports:
            - 8082:80
        volumes:
            - .:/var/www/html
    notification-postgres:
        container_name: notification-postgres
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: 'notification'
            POSTGRES_USER: 'notification'
            POSTGRES_PASSWORD: 'notification123'
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - notificationdb-data:/var/lib/postgresql/data
        ports:
            - "25432:5432"
volumes:
    notificationdb-data:
