version: "3.3"
services:
    laravel-app:
#        image: sapronovps/otus-microservice-architecture:latest
        build:
            context: '.'
            args:
                uid: ${UID}
        container_name: laravel-app
        ports:
            - 8080:80
#        volumes:
#            - .:/var/www/html
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: 'otus'
            POSTGRES_USER: 'otus'
            POSTGRES_PASSWORD: 'otus123'
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - otusdb-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    otusdb-data:
