{
 "title": "Otus Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Среднее время ответа сервера",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Otus RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "delta(otus_rps[$__interval])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Квантиль по Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (quantile) (rate(otus_latency[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otus 500 Ошибки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(otus_errorResponse[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}