{
 "title": "Мониторинг Kubernetes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Объем памяти контейнера сервера метрик в байтах",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "delta(container_memory_usage_bytes{namespace=\"otus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Совокупное системное процессорное время, затраченное в секундах.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{namespace=\"otus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальное использование памяти, записанное в байтах",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(container_memory_max_usage_bytes{namespace=\"otus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Совокупное время, затраченное процессором, измеряется в секундах.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"otus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Совокупное процессорное время пользователя, затраченное в секундах.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{namespace=\"otus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Значение средней загрузки процессора контейнера за последние 10 секунд",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{namespace=\"otus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}