version: "3.3"
services:
    shop-app:
#        image: sapronovps/otus-microservice-architecture:latest
        build:
            context: '.'
            args:
                uid: ${UID}
        container_name: shop-app
        ports:
            - 8080:80
        networks:
            - otus-network
        volumes:
            - .:/var/www/html
    shop-postgres:
        image: postgres:15-alpine
        container_name: shop-postgres
        environment:
            POSTGRES_DB: 'shop'
            POSTGRES_USER: 'shop'
            POSTGRES_PASSWORD: 'shop123'
            PGDATA: "/var/lib/postgresql/data/pgdata"
        networks:
            - otus-network
        volumes:
            - shopdb-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
networks:
    otus-network:
        driver: bridge
volumes:
    shopdb-data:
