apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /health/$2
  name: order-ingress-rewrite
  namespace: {{ .Values.namespace }}
spec:
    ingressClassName: nginx
    rules:
      - host: order.homework
        http:
          paths:
            - pathType: ImplementationSpecific
              backend:
                service:
                  name: {{ .Values.serviceName }}
                  port:
                    number: {{ .Values.image.port }}
              path: /otusapp/(.*)/health
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: order-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: order.homework
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: {{ .Values.image.port }}
            path: /

