apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-delivery2-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi