apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-billing-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume2"