apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
      nodePort: 30000
  selector:
    app: {{ .Values.appName }}