version: "3.3"
services:
    warehouse-app:
#        image: sapronovps/otus-microservice-architecture:latest
        build:
            context: '.'
            args:
                uid: ${UID}
        container_name: warehouse-app
        ports:
            - 8080:80
        networks:
            - otus-network
        volumes:
            - .:/var/www/html
    warehouse-postgres:
        image: postgres:15-alpine
        container_name: warehouse-postgres
        environment:
            POSTGRES_DB: 'warehouse'
            POSTGRES_USER: 'warehouse'
            POSTGRES_PASSWORD: 'warehouse123'
            PGDATA: "/var/lib/postgresql/data/pgdata"
        networks:
            - otus-network
        volumes:
            - warehousedb-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
networks:
    otus-network:
        driver: bridge
volumes:
    warehousedb-data:
