version: "3.3"
services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/app
        links:
            - php-fpm
        ports:
            - "80:80"
    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/app
        ports:
            - "9000:9000"
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: 'otus'
            POSTGRES_USER: 'otus'
            POSTGRES_PASSWORD: 'otus123'
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - otusdb-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    otusdb-data:
