auth:
    enablePostgresUser: true
    postgresPassword: "12345"
    username: "otus"
    password: "1234"
    database: "otus"

primary:
    persistence:
        enabled: true
        existingClaim: "pgsql-delivery2-data-claim"
    service:
        ports:
            postgresql: 5435

ServiceMonitor:
    namespace: otus

volumePermissions:
    enabled: true